module Pestle::Grammar
  # Pest grammar parsing error.
  class PestGrammarError < StandardError
    @token: [Symbol, String?, Integer]

    @source: String

    attr_accessor token: [Symbol, String?, Integer]

    attr_accessor source: String

    FULL_MESSAGE: bool

    def initialize: (String message, String source, [Symbol, String?, Integer] token) -> void

    def detailed_message: (?highlight: bool, **untyped kwargs) -> String

    def full_message: (?highlight: bool, ?order: ::Symbol) -> String

    def error_context: (String source, Integer index) -> [Integer, Integer, String]
  end
end