module Pestle::Grammar
  class Range < Terminal
    @start: String

    @stop: String
    
    @re: Regexp

    attr_reader start: String

    attr_reader stop: String

    def initialize: (String start, String stop, ?tag: String?) -> void

    def parse: (Pestle::ParserState state, Array[Pestle::Pair] pairs) -> bool
  end
end

