module Pestle::Grammar
  class Rule < Expression
    @name: String

    @expression: Expression

    @modifier: Integer

    @doc: String?

    attr_reader name: String

    attr_reader modifier: Integer

    attr_reader doc: String?

    SILENT: Integer

    ATOMIC: Integer

    COMPOUND: Integer

    NONATOMIC: Integer

    SILENT_ATOMIC: Integer

    SILENT_COMPOUND: Integer

    SILENT_NONATOMIC: Integer

    def initialize: (String name, Expression expression, ?modifier: Integer, ?doc: String?) -> void

    def parse: (Pestle::ParserState state, Array[Pestle::Pair] pairs) -> bool
  
    def children: () -> ::Array[Expression]
  end

  class BuiltInRule < Rule
  end
end