plugins:
  - rubocop-minitest
  - rubocop-rake
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 50

Metrics/ParameterLists:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

Naming/MethodParameterName:
  AllowedNames: [op, re]

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Minitest/AssertPredicate:
  Enabled: false
